# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sergio/Projects/C++/ARCE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sergio/Projects/C++/ARCE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergio/Projects/C++/ARCE/CMakeFiles /home/sergio/Projects/C++/ARCE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergio/Projects/C++/ARCE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ARCE

# Build rule for target.
ARCE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ARCE
.PHONY : ARCE

# fast build rule for target.
ARCE/fast:
	$(MAKE) -f CMakeFiles/ARCE.dir/build.make CMakeFiles/ARCE.dir/build
.PHONY : ARCE/fast

#=============================================================================
# Target rules for targets named algos

# Build rule for target.
algos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 algos
.PHONY : algos

# fast build rule for target.
algos/fast:
	$(MAKE) -f src/algos/CMakeFiles/algos.dir/build.make src/algos/CMakeFiles/algos.dir/build
.PHONY : algos/fast

#=============================================================================
# Target rules for targets named automata

# Build rule for target.
automata: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 automata
.PHONY : automata

# fast build rule for target.
automata/fast:
	$(MAKE) -f src/automata/CMakeFiles/automata.dir/build.make src/automata/CMakeFiles/automata.dir/build
.PHONY : automata/fast

#=============================================================================
# Target rules for targets named bot_ARCE

# Build rule for target.
bot_ARCE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bot_ARCE
.PHONY : bot_ARCE

# fast build rule for target.
bot_ARCE/fast:
	$(MAKE) -f src/bot_ARCE/CMakeFiles/bot_ARCE.dir/build.make src/bot_ARCE/CMakeFiles/bot_ARCE.dir/build
.PHONY : bot_ARCE/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ARCE.dir/build.make CMakeFiles/ARCE.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ARCE.dir/build.make CMakeFiles/ARCE.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ARCE.dir/build.make CMakeFiles/ARCE.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ARCE"
	@echo "... edit_cache"
	@echo "... algos"
	@echo "... automata"
	@echo "... bot_ARCE"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

